# Generated by Django 4.1 on 2022-12-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchine',
            name='acao',
            field=models.BooleanField(default=False),
        ),
    ]
