# Generated by Django 4.1 on 2022-12-12 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marchine', '0003_alter_marchine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchine',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
